Mikibo refactor map buttons
andrew-bierman/PackRat pull request #124
Opened 2023-07-09 14:22 UTC by mikib0

2023-07-09 19:32 UTC, andrew-bierman commented
nice work, i'm getting a couple of errors trying to use the buttons such as the location, switching through styles.

2023-07-09 22:04 UTC, andrew-bierman commented
It looks like preview map zoom is not showing trail the way it was previously.
![Screenshot 2023-07-09 at 6 03 51 PM](https://github.com/andrew-bierman/PackRat/assets/94939237/72112fd6-a0dc-4c86-a064-2a9fad676cf0)

2023-07-09 22:09 UTC, andrew-bierman requested changes
Looks good overall, just need to fix up a couple functionality things / errors and this is good to merge. See comments when possible please.

2023-07-09 22:09 UTC, andrew-bierman commented on client/utils/mapFunctions.js
> +import { saveAs } from 'file-saver';
I think file saver throws errors if it compiles on native due to trying to use the DOM. We might need to find a better library for cross platform file, or put the file saving logic in .web and .native files respectively

2023-07-09 22:09 UTC, andrew-bierman commented on client/components/map/MapButtonsOverlay.js
On iOS devices with notch, top buttons are too far in top. MIght need to do a SafeAreaView to stop that

2023-07-09 22:09 UTC, andrew-bierman commented on client/components/map/NativeMap.native.js
Preview map zoom not properly fitting trail anymore

2023-07-09 22:09 UTC, andrew-bierman commented on client/components/map/MapButtonsOverlay.js
Mapbox errors on location button, changing through styles in full screen mode

2023-07-10 16:14 UTC, mikib0 commented
> 

Ah, I see. But switching styles work right, eventhough some errors get thrown. I also now get this "No location provider available" error when I click the location button. This is odd, everything was working w/o errors yesterday 😬😀. But it is alright, I'll check them.

2023-07-10 16:15 UTC, mikib0 commented on client/components/map/NativeMap.native.js
Fixed👍

2023-07-10 16:17 UTC, mikib0 commented on client/components/map/MapButtonsOverlay.js
I wrapped the component in a SafeAreaView; Please check again if the problem is resolved.

2023-07-10 18:26 UTC, mikib0 commented on client/components/map/MapButtonsOverlay.js
For the location problem...is the device's location turned on? The functionality worked and I stopped getting the error after I turned on my phone's location.

2023-07-10 18:32 UTC, mikib0 commented on client/components/map/MapButtonsOverlay.js
The errors on changing styles seem go away too after turning on the location.

2023-07-10 18:44 UTC, mikib0 commented on client/utils/mapFunctions.js
> +import { saveAs } from 'file-saver';
Yea we can just simply implement the logic differently for each platform.

2023-07-10 18:52 UTC, andrew-bierman commented on client/utils/mapFunctions.js
> +import { saveAs } from 'file-saver';
Yes, I went ahead and added some custom imports to address this based on platform

2023-07-11 00:34 UTC, andrew-bierman commented on client/components/map/MapButtonsOverlay.js
Can we prompt for the location with that expo location library ? I think we can, that might improve the UX

2023-07-11 00:42 UTC, andrew-bierman commented on client/components/map/MapButtonsOverlay.js
iOS throwing this on location press, with location permissions enabled 

` ERROR  Mapbox error CameraUpdateItem.execute  paramError("latitude should be between -90 and 90 but it was -122.406417") {"level": "error", "message": "CameraUpdateItem.execute  paramError(\"latitude should be between -90 and 90 but it was -122.406417\")"}
› Reloading apps`

2023-07-11 00:53 UTC, andrew-bierman commented on client/components/map/MapButtonsOverlay.js
Seems to still persist and some iOS cuts off the buttons entirely. Might need to do something with the StatusBar from react native and maybe pass that value in with some padding like marginTop: StatusBar.currentHeight + 20. Just an idea, not sure if this would work

2023-07-11 01:04 UTC, andrew-bierman commented
On web, we had to remove the style layers before adding new ones. Might need to see if something like that can be done with RNMapbox

2023-07-11 13:00 UTC, mikib0 commented
> On web, we had to remove the style layers before adding new ones. Might need to see if something like that can be done with RNMapbox

I don't think it's necessary to do something like that on mobile, because we are rerendering the component when the style changes. Or what do you think?

2023-07-11 13:49 UTC, mikib0 commented on client/components/map/MapButtonsOverlay.js
> Can we prompt for the location with that expo location library ? I think we can, that might improve the UX

Right, I'll look into this.

>  ERROR  Mapbox error CameraUpdateItem.execute  paramError("latitude should be between -90 and 90 but it was -122.406417") {"level": "error", "message": "CameraUpdateItem.execute  paramError(\"latitude should be between -90 and 90 but it was -122.406417\")"} › Reloading apps

This is strange. Please check (maybe the `custom location` config) if the latitude value is within the valid range.

2023-07-11 23:07 UTC, andrew-bierman commented on client/components/map/MapButtonsOverlay.js
On android do you not get that CameraUpdateItem error ?

2023-07-12 09:25 UTC, mikib0 commented on client/components/map/MapButtonsOverlay.js
No, I don't.

2023-07-17 01:00 UTC, andrew-bierman commented
I'm going to merge this in to keep the andrew_testing branch up to speed, but if you could review my feedback and make sure we covered everything that would be great @mikib0

2023-07-17 01:01 UTC, andrew-bierman approved these changes
lgtm

2023-07-17 01:01 UTC, merged