Umang
andrew-bierman/PackRat pull request #210
Opened 2023-08-03 20:43 UTC by gucci1909

middleware , redux token in api's and Basic Item Recommendation Algorithm

2023-08-03 21:05 UTC, andrew-bierman commented on client/store/authStore.js
> +      await AsyncStorage.setItem('userToken', token); // Save token in local storage
is there a reason we are not just using our redux persist integration for this ?

2023-08-03 21:05 UTC, andrew-bierman commented on client/store/chatStore.js
> +      const token = await AsyncStorage.getItem('userToken');
Could this be done with middleware or at the very least a helper function? Just trying to minimize duplicate code.

2023-08-03 21:05 UTC, andrew-bierman commented on client/store/destinationStore.js
> +      const token = await AsyncStorage.getItem('userToken');
We should just add a middleware to our store like this, would cut down on a top of repeated code. Rough idea:

`const authMiddleware = (storeAPI) => (next) => (action) => {
  if (action.type.includes('pending')) {
    const token = storeAPI.getState().auth.token;

    if (token) {
      // Attach token to headers
      action.meta.arg.headers = { ...action.meta.arg.headers, Authorization: `Bearer ${token}` };
    }
  }

  return next(action);
};
`

2023-08-03 22:35 UTC, andrew-bierman requested changes
See comments

2023-08-03 23:07 UTC, andrew-bierman commented
I'm getting 'invalid token' error for all API requests. Are you experiencing same thing ?

2023-08-04 16:35 UTC, gucci1909 commented
> I'm getting 'invalid token' error for all API requests. Are you experiencing same thing ?

yes @andrew-bierman same

2023-08-04 17:27 UTC, andrew-bierman commented
These should be split into different pull requests

2023-08-04 18:58 UTC, closed without merging