Mikibo save geojson for destination
andrew-bierman/PackRat pull request #231
Opened 2023-08-09 21:36 UTC by mikib0

Save geojson to db directly instead of modelling osm types. This will simplify lots of things and fix lots of the issues faced with saving osm while also preventing duplication.

2023-08-09 22:55 UTC, andrew-bierman commented
Thanks for this, but looks like we are missing the geojson model you referenced. Did you intend to have a model for this, or just include geojson  in one of the other schemas?

2023-08-09 22:56 UTC, andrew-bierman requested changes

2023-08-09 22:56 UTC, andrew-bierman commented on server/controllers/tripController.js
> +import GeoJSON from "../models/geojsonModel.js";
missing file

2023-08-10 06:59 UTC, mikib0 commented on server/controllers/tripController.js
> +import GeoJSON from "../models/geojsonModel.js";
forgot to include it in the commit 😅

2023-08-11 01:34 UTC, andrew-bierman approved these changes
nicely done

2023-08-11 01:34 UTC, merged