WIP - Server, Mongoose -> Prisma. Hono integration.
andrew-bierman/PackRat pull request #483
Opened 2023-11-11 01:22 UTC by andrew-bierman

2023-11-15 22:06 UTC, awais-codes commented
1. Setup standalone tRPC setup i.e no elysia.
2. Replaced bcrypt with bcryptjs
3. updated server package.json script and .ignore
4. commented user routes
5. updated prisma imports to use edge based client.

2023-12-09 03:23 UTC, andrew-bierman commented
Below are some queries that I'm running into issues with on my side, I think mostly due to response size/length. We should be more explicit about the data we need (based on frontend). List is in progress still. 

We have strict [limitations](https://www.prisma.io/docs/accelerate/limitations) using the accelerate/data proxy from prisma.

- [ ] getPacks
- [ ] getPublicPacks
- [ ] getTrips
- [ ] getPublicTrips
- [ ] getUserFavorites

2023-12-09 22:16 UTC, andrew-bierman commented
- [ ] getPhotonResults cannot read properties of undefined

2023-12-10 20:31 UTC, andrew-bierman commented
Note, need to add values from env to env.dev.vars in wrangler toml for development environment. Be sure not to commit these to repo.

2023-12-11 14:04 UTC, andrew-bierman commented
DATABASE_URL will need to be updated to a prisma connection pooling URL for something like prisma accelerate to work properly on edge

2023-12-15 00:45 UTC, yasTheDreamer requested changes

2023-12-15 00:45 UTC, yassinecodes201 commented on server/src/prisma/schema.prisma
> +  url      = env("MONDODB_URI")
```suggestion
  url      = env("MONGODB_URI")
```

2023-12-15 00:45 UTC, yassinecodes201 commented on server/src/services/favorite/getUserFavoritesService.ts
> +      favorites: true,
```suggestion
      favoriteDocuments: true,
```

2023-12-15 00:45 UTC, yasTheDreamer commented on server/src/prisma/statics/node.ts
> +const findOrCreateMany = async (ids, nodes) => {
to fix error : `this `might be undefined
```suggestion
async function findOrCreateMany(ids, nodes) {
```

2026-03-08 22:17 UTC, andrew-bierman commented
Closing stale PR from February 2024. Branch has merge conflicts with main.

2026-03-08 22:17 UTC, closed without merging