Fix/add types and interfaces in components
andrew-bierman/PackRat pull request #589
Opened 2024-01-11 18:10 UTC by jitprosen360

Component files adding types and interfaces

2024-01-13 01:23 UTC, andrew-bierman requested changes
please rebase or copy changes to latest file structure

2024-01-13 01:23 UTC, andrew-bierman commented on client/app.example.json
don't delete example file

2024-01-13 12:14 UTC, jitprosen360 commented on client/app.example.json
solved

2024-01-14 19:52 UTC, andrew-bierman commented
these should be going into the /packages/app directory now, not /client directory. copy these changes to a clean branch off of andrew_testing please

2024-01-17 11:38 UTC, closed without merging