fix: feed quick actions and search bar
andrew-bierman/PackRat pull request #620
Opened 2024-01-18 00:00 UTC by imrizwan

- feed fixed
- search bar fixed
- quick actions fixed
on native side

2024-01-18 03:56 UTC, andrew-bierman approved these changes
lgtm

2024-01-23 01:31 UTC, andrew-bierman requested changes
see comments, this is almost ready to go though

2024-01-23 01:31 UTC, andrew-bierman commented on packages/app/components/pack/PackDetails.tsx
> +      const searchParams = new URLSearchParams(this.location.search);
I don't know why we hardcoded for web here, but we should update this to be cross platform with solito

2024-01-23 01:31 UTC, andrew-bierman commented on packages/app/components/user/UserDataContainer.tsx
> +            Platform.OS === 'web' ? <FlatList
I'd probably prefer to go flat list on both for perf if possible. Maybe horizontal flat list with show all button? Or maybe open these sections in their own modals with flat list in there?

2024-01-23 09:31 UTC, imrizwan commented on packages/app/components/pack/PackDetails.tsx
> +      const searchParams = new URLSearchParams(this.location.search);
Changed to solito for cross platform

2024-01-23 12:28 UTC, imrizwan commented on packages/app/components/user/UserDataContainer.tsx
> +            Platform.OS === 'web' ? <FlatList
Converted flatlist to virtualized list, and made a different structure to remove virtualized list error

2024-01-23 19:31 UTC, imrizwan commented
> see comments, this is almost ready to go though

Comments resolved

2024-01-24 03:35 UTC, andrew-bierman commented
pack details on web is blank for me, might just be my next environment, looking into it

2024-02-04 16:02 UTC, andrew-bierman commented
pack details still blank on my side, are you noticing the same ?

2024-02-04 17:26 UTC, imrizwan commented
> pack details still blank on my side, are you noticing the same ?

I am receiving this on pack details page
<img width="822" alt="image" src="https://github.com/andrew-bierman/PackRat/assets/17934962/9fa6b51e-3692-4f06-83d4-34c54494c188">

2024-02-05 09:50 UTC, imrizwan commented
> pack details still blank on my side, are you noticing the same ?

 - No, Seems to be working fine, but let me check if there's any problem

2024-02-10 23:36 UTC, andrew-bierman approved these changes

2024-02-10 23:36 UTC, andrew-bierman commented on packages/app/components/pack/PackDetails.tsx
> +  const getParams = () => {
Pretty sure the logic in here is causing pack details to be blank 🤔 otherwise I think we can get this merged

2024-02-10 23:36 UTC, merged